#name = input("Enter you full name : ")
#phone_number= input("Enter you phone number")
#result = len(name)
#result = name.find("o")
#result = name.rfind("6")
#result = name.capitalize()
#result = name.upper()
#result = name.lower()
#result = name.isdigit()
#result = name.isalpha()
#result = phone_number.count("-")
#result = phone_number.replace("-"," ")
#result = phone_number.replace("-","")
#print(result)

print(help(str))